# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            msdalp
tagline:          java, android, etc.
url:              msdalp.github.io
paginate:         1
baseurl:          /
author:
  name:           Mustafa Alparslan
  url:            www.msdalp.github.io
  email:          msdalp@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/msdalp
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
