# Permalinks
permalink:        pretty

gems: [jekyll-paginate]
paginate:         1

# Setup
title:            msdalp
tagline:          java, android, etc.
url:              http://msdalp.github.io
comments:         true
disqus-shortname: msdalp
baseurl:          /
author:
  name:           Mustafa Alparslan
  url:            www.msdalp.github.io
  email:          msdalp@gmail.com

# Custom vars
version:          1.1.0
github:
  repo:           https://github.com/msdalp

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
